#!/bin/sh
# https://github.com/shvedes/dotfiles 

# generate 10 workspaces on 1 monitor
bspc monitor -d I II III IV V VI VII VIII IX X

##### configs

bspc config window_gap                 10          # windows gaps
bspc config border_width               2           # border size
bspc config pointer_motion_interval    30          # the minimum interval, in milliseconds, between two motion notify events 

##### themes

# catppuccin theme
# $HOME/.config/bspwm/colors/gruvbox-dark.sh

# gruvbox theme 
$HOME/.config/bspwm/colors/gruvbox-dark.sh

##### window rules

bspc config external_rules_command "$HOME/.local/bin/bspwm/external-rules.sh"

bspc rule -a Code            desktop='^1' follow=on  center=on
bspc rule -a Spotify         desktop='^2' follow=off state=pseudo_tiled     center=on 
bspc rule -a firefox         desktop='^3' follow=off center=off
bspc rule -a TelegramDesktop desktop='^4' follow=off center=on
bspc rule -a obs             desktop='^5' follow=off state=floating         center=on
bspc rule -a Thunar          desktop='^6' follow=on  state=floating         center=on  rectangle=1300x800+0+0
bspc rule -a mpv             desktop='^7' follow=on  state=tiled            center=on 
bspc rule -a feh             desktop='^7' follow=on  state=tiled            center=on
bspc rule -a qBittorrent     desktop='^9' follow=on  state=floating         center=on  rectangle=1200x650+0+0

##### autostart scripts
$HOME/.local/bin/bspwm/startup.sh &
