#!/bin/bash
# https://github.com/shvedes/dotfiles

bspc config normal_border_color        \#4f5b66     
bspc config focused_border_color       \#c678dd     
bspc config active_border_color        \#c678dd     
